- hosts: all
    tasks:
  - name: stop container
    shell: docker container stop rockstar-container
  - name: remove container
    shell: docker container rm rockstar-container
  - name: remve docker image
    shell: docker image rm magicalboy26/docker-prt
  - name: create new container
    shell: docker container run -itd --name rockstar-container -p 9090:80 magicalboy26/docker-prt
